# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from control.display import display_to_ui

class Ui_MainWindow(object):

    def __init__(self):
        self.l = display_to_ui()
        self.l.dele_of_que()
        self.l.init_random_data()
        self.s = self.l.get_list("../ques.txt")
        self.res = self.l.get_list_res("../reuslt.txt")
        self.num = 0
        self.socre = 0
        self.status = []
        self.dic = dict()
        for i in range(len(self.s)):
            self.status.append(0)


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(623, 446)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(140, 10, 301, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 60, 581, 131))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(430, 210, 91, 31))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 210, 311, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(190, 290, 186, 28))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.pushButton_up = QtWidgets.QPushButton(self.splitter)
        self.pushButton_up.setObjectName("pushButton_up")
        self.pushButton_next = QtWidgets.QPushButton(self.splitter)
        self.pushButton_next.setObjectName("pushButton_next")
        self.label_ques = QtWidgets.QLabel(self.centralwidget)
        self.label_ques.setGeometry(QtCore.QRect(520, 20, 72, 15))
        self.label_ques.setText("")
        self.label_ques.setObjectName("label_ques")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(210, 350, 161, 31))
        self.label_status.setText("")
        self.label_status.setObjectName("label_status")
        self.label_select = QtWidgets.QLabel(self.centralwidget)
        self.label_select.setGeometry(QtCore.QRect(30, 20, 72, 15))
        self.label_select.setText("")
        self.label_select.setObjectName("label_select")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(510, 310, 71, 31))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.textBrowser_score = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_score.setObjectName("textBrowser_score")
        self.horizontalLayout_2.addWidget(self.textBrowser_score)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 623, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.retranslateUi(MainWindow)
        self.label_ques.setText(str(self.num)+'/'+str(len(self.s)))
        self.label_select.setText("单选题")
        self.retranslateUi(MainWindow)

        self.pushButton_up.clicked.connect(self.pash_up)
        self.pushButton_next.clicked.connect(self.pash_next)
        self.pushButton.clicked.connect(self.confirm)
        self.textBrowser_2.setText(str(self.num + 1) + self.s[self.num][self.s[self.num].index('、'):])


        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def pash_up(self):
        self.num -= 1

        if self.num < 0 or self.num > 82:
            self.num = 0


        self.textBrowser_2.setText(str(self.num + 1) + self.s[self.num][self.s[self.num].index('、'):])

        self.label_ques.setText(str(self.num+1) + '/' + str(len(self.s)))
        self.label_status.setText("")
        self.textEdit.setText("")
        self.textBrowser_score.setText(str(self.socre))

        if self.num+1 > 41 and self.num+1 <63:
            self.label_select.setText("多选题")
        if self.num + 1 >= 63 :
            self.label_select.setText("判断题")
        if self.status[self.num] == 1:
            self.label_status.setText("你往期答案为：" + self.dic[self.num])

    def pash_next(self):
        self.num += 1

        if self.num < 0 or self.num > 82:
            self.num = 0

        self.textBrowser_2.setText(str(self.num+1)+self.s[self.num][self.s[self.num].index('、'):])

        self.label_ques.setText(str(self.num+1) + '/' + str(len(self.s)))
        self.textEdit.setText("")
        self.label_status.setText("")
        self.textBrowser_score.setText(str(self.socre))

        if self.num+1 > 41 and self.num+1 <63:
            self.label_select.setText("多选题")
        if self.num + 1 >= 63 :
            self.label_select.setText("判断题")
        if self.status[self.num] == 1:
            self.label_status.setText("你往期答案为："+self.dic[self.num])
    def confirm(self):

        if self.textEdit.toPlainText() == "":
            self.label_status.setText("答案不能为空")
        else:
            if self.status[self.num] == 1:
                self.label_status.setText("你往期答案为："+self.dic[self.num])
            else:
                self.status[self.num] = 1
                p = self.textEdit.toPlainText()
                self.dic[self.num] = p
                if(self.res[self.num][:1] == p):
                    self.label_status.setText("正确")
                    if self.num + 1 > 41 and self.num + 1 < 63:
                        self.socre += 2
                    else:
                        self.socre += 1
                else:
                    self.label_status.setText("正确答案为："+self.res[self.num])


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">毛概模拟考</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "确认"))
        self.label.setText(_translate("MainWindow", "输入你的答案"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_up.setText(_translate("MainWindow", "上一题"))
        self.pushButton_next.setText(_translate("MainWindow", "下一题"))
        self.label_2.setText(_translate("MainWindow", "分数"))
        self.textBrowser_score.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">0</span></p></body></html>"))
